image:
  - Visual Studio 2015

environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
    - PYTHON: "C:\\Python27"
      CPP: 14
    - PYTHON: "C:\\Python27-x64"
      CPP: 14
  

build_script:
  - '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - pip install cibuildwheel
  - pip install pybind11
  - cibuildwheel --output-dir wheelhouse

test_script:
  - python setup.py test

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels